---
- name: install initial packages on all boxes
  hosts: 192.168.1.14
  remote_user: ansible
  become: yes
  tasks:
  - name: install chrony
    yum:
      name: chrony
      state: latest

  - name: configure chrony
    template:
      src: /home/ansible/ansible/playbooks/chrony.client.j2
      dest: /etc/chrony.conf
  - name: start chronyd
    service:
      name: chronyd
      state: started
      enabled: true
  - name: restart chronyd
    service:
      name: chronyd
      state: restarted
